#!/bin/bash

unset -f ssh-dev >/dev/null 2>&1;
unset -f ssh-prod >/dev/null 2>&1;

unset -f ssh-new >/dev/null 2>&1;
unset -f ssh-aws-micro-tester-1 >/dev/null 2>&1;

unset -f mysql-create-dump >/dev/null 2>&1;
unset -f mysql-load-dump >/dev/null 2>&1;
unset -f mysql-recreate-db >/dev/null 2>&1;

unset DJANGO_SETTINGS_MODULE >/dev/null 2>&1;
unset DATABASE_URL >/dev/null 2>&1;
